name: Release Binary

on: [push, pull_request]

jobs:
  build-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version or commit hash
        id: version
        run: echo "version=$(git describe --always --dirty)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Build for MacOS
        run: |
          cargo build --target aarch64-apple-darwin --release

      - name: Upload binary
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ steps.version.outputs.version }}
          path: target/aarch64-apple-darwin/release/search-word
          compression-level: 9
          overwrite: true

      - name: Add artifact download link to summary
        run: |
          echo "### Binary Download 📦" >> $GITHUB_STEP_SUMMARY
          echo "[Download binary-${{ steps.version.outputs.version }}](${{ steps.upload.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY
          echo "curl -L '${{ steps.upload.outputs.artifact-url }}' -o search-word && chmod +x search-word" >> "$GITHUB_STEP_SUMMARY"
