name: Rust ARM64 Build

on: [push, pull_request]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version or commit hash
        id: version
        run: echo "version=$(git describe --always --dirty)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install ARM64 cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Configure cross-compilation
        run: |
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml

      - name: Build for ARM64
        run: |
          cargo build --target aarch64-unknown-linux-gnu --release

      - name: Upload ARM64 binary
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binary-${{ steps.version.outputs.version }}
          path: target/aarch64-unknown-linux-gnu/release/search-word
          compression-level: 9
          overwrite: true

      - name: Add artifact download link to summary
        run: |
          echo "### ARM64 Binary Download 📦" >> $GITHUB_STEP_SUMMARY
          echo "[Download arm64-binary-${{ steps.version.outputs.version }}](${{ steps.upload.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY